# This is a basic workflow to help you get started with Actions

name: Test-workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set Target
      run: echo "TARGET_BUILD_NAME=SqueezeAmp" >> $GITHUB_ENV
    - name: Get Target
      run: echo "Target is ${TARGET_BUILD_NAME}"
