# This is a basic workflow to help you get started with Actions

name: SqueezeAmp

on:
  push:
    branches: [ master-cmake ]
  pull_request:
    branches: [ master-cmake ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set target
      run: echo '::set-output name=TARGET_BUILD_NAME::SqueezeAmp'
      id: target-name-generator
    - name: Get color
      run: echo "Target is ${{steps.target-name-generator.outputs.TARGET_BUILD_NAME}}"
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}        
    - name: Cache build
      id: cache-build
      uses: actions/cache@v1
      with:
        path: ${{github.workspace}}/build
        key: ${{ runner.os }}-${{ steps.target-name-generator.outputs.TARGET_BUILD_NAME}}
    - name: Build the firmware
      run: |
        docker run --rm -v $PWD:/project -w /project espressif/idf:release-v4.0 /bin/bash -c "cp build-scripts/${{ steps.target-name-generator.outputs.TARGET_BUILD_NAME}}-sdkconfig.defaults sdkconfig && export PROJECT_VER=${{ steps.target-name-generator.outputs.TARGET_BUILD_NAME}}-${{ steps.buildnumber.outputs.build_number }} && idf.py build"